- name: Remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create /etc/resolv.conf with custom DNS nameservers
  copy:
    content: |
      nameserver 10.202.10.202
      nameserver 10.202.10.102
    dest: /etc/resolv.conf
