- name: Initialize Kubernetes Cluster with kubeadm
  shell: kubeadm init --upload-certs --apiserver-advertise-address {{ ansible_default_ipv4.address }} --control-plane-endpoint {{ ansible_default_ipv4.address }}:6443 --pod-network-cidr={{ pod_cidr }}
  register: kubeadm_output

- name: Save the Result of the kubeadm init command
  local_action:
    module: copy
    content: "{{ kubeadm_output.stdout }}"
    dest: /home/ansible/kubeadm_init_result.log
    force: yes

- name: Add KUBECONFIG to root Bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    backup: yes

- name: Create kubeconfig.sh script
  copy:
    content: |
      #!/bin/bash
      export KUBECONFIG=/etc/kubernetes/admin.conf
      kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml > /dev/null 2>&1
    dest: /tmp/kubeconfig.sh
    mode: '0755'

- name: Run kubeconfig.sh
  script: /tmp/kubeconfig.sh

- name: Remove kubeconfig.sh
  file:
    path: /tmp/kubeconfig.sh
    state: absent
