- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ base_install_packages }}"

- name: Download Docker GPG key
  uri:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    owner: root
    group: root
    mode: 0600

- name: Import gpg key
  shell: "cat /tmp/docker.gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg --yes"

- name: Delete /tmp/docker.gpg file
  file:
    path: /tmp/docker.gpg
    state: absent

      
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

      #- name: Create Docker repository line
      #template:
      #src: docker_repository.j2
      #dest: /etc/apt/sources.list.d/docker.list
