- name: Update package cache
  apt:
    update_cache: yes

- name: Install containerd.io
  apt:
    name: containerd.io
    state: present

- name: Configure Containerd
  command: containerd config default > /etc/containerd/config.toml

    - name: Modify Containerd configuration
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemCgroup = true'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Restart Containerd service
  systemd:
    name: containerd
    state: restarted
