- name: Install containerd.io
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Run containerd config command and save output to file
  command: containerd config default
  register: containerd_config_output

- name: Write containerd config output to file
  ansible.builtin.copy:
    content: "{{ containerd_config_output.stdout }}"
    dest: /etc/containerd/config.toml

- name: Modify Containerd configuration
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemCgroup = true'
  notify:
    - Reload systemd daemon
    - Restart containerd service
