- name: Download Kubernetes GPG key
  uri:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/kubernetes.gpg
    owner: root
    group: root
    mode: 0600

- name: Import gpg key
  shell: "cat /tmp/kubernetes.gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/kubernetes-xenial.gpg --yes"

- name: Delete /tmp/kubernetes.gpg file
  file:
    path: /tmp/kubernetes.gpg
    state: absent

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

#- name: Copy Kubernetes repository configuration
  #copy:
    #content: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    #dest: /etc/apt/sources.list.d/kubernetes.list
    #force: yes

- name: Install Kubernetes components
  apt:
    name: "{{ kuber_component_packages }}"
    state: present
    update_cache: yes

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ kuber_component_packages }}" 
