- name: reset prev kuber settings
  include_tasks: reset_kubernetes.yml

- name: extract worker's join command
  shell: awk '/kubeadm join/{count++; if (count == 2) {print; getline; print; exit;}}' /root/kubeadm_init_result.log
  register: worker_join_command

- name: Execute kubeadm worker join command
  shell: "{{ worker_join_command.stdout }}"
  when: worker_join_command.stdout_lines | length > 0

- name: Delete the worker join command file
  file:
    path: /root/kubeadm_init_result.log
    state: absent
