- name: reset prev kuber settings
  include_tasks: reset_kubernetes.yml

- name: get join master command
  shell: awk '/kubeadm join/{y=1}y && /\\/ {print;next}y && !/\\/ {print;exit}' /root/kubeadm_init_result.log
  register: master_join_command

- name: Execute kubeadm join command
  shell: "{{ master_join_command.stdout }}"
  when: master_join_command.stdout_lines | length > 0

- name: Delete the master join command file
  file:
    path: /root/kubeadm_init_result.log
    state: absent
