- name: Extract Join Command from Log File
  command: grep -E -o 'kubeadm join .+' /root/kubeadm_init_result_kmaster.log
  register: join_command

- name: Joining the Node to The Cluster
  shell: "{{ join_command.stdout }}"
