# tasks file for kubernetes_containerd_installation

- name: disable swap
  include_tasks: disable_swap.yml
    
- name: configure dns settings
  include_tasks: conf_dns.yml

- name: install docker repo
  include_tasks: install_docker_repo.yml

- name: install containerd.io
  include_tasks: install_containerd.yml

- name: probe modules & config linux kernel modules
  include_tasks: probe_modules.yml

- name: apply changes in sysctl 
  include_tasks: conf_sysctl.yml
