- name: Configure Linux kernel modules for Containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    create: yes
    block: |
      overlay
      br_netfilter

- name: Load kernel modules overlay
  modprobe:
    name: overlay
    state: present

- name: Load kernel modules br_netfilter
  modprobe:
    name: br_netfilter
    state: present
