- name: Reset Kubernetes (kubeadm reset)
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove Previous Configs
  file:
    state: absent
    dest: "{{ ansible_env.HOME }}/.kube/config"

- name: Unset KUBECONFIG environment variable
  environment:
    KUBECONFIG: ""
