- name: Reset Kubernetes (kubeadm reset)
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove Previous Configs
  file:
    state: absent
    dest: "{{ ansible_env.HOME }}/.kube/config"

- name: Remove Kubernetes Configs and data
  file:
    state: absent
    dest: "/etc/kubernetes/"

- name: Unsetenv KUBECONFIG environment variable
  shell: unset KUBECONFIG
