# handlers file for kubernetes_containerd_installation

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Restart containerd service
  systemd:
    name: containerd.service
    state: restarted

- name: Apply sysctl settings
  command: sysctl --system
